BoxLayout:
    orientation: "vertical"
    padding: "10dp"

    Image:
        id: image
        source: None

    BoxLayout:
        spacing: 2

        Button:
            id: button_yes
            font_size: "20dp"
            height: "50dp"
            size_hint_y: None

        Button:
            id: button_no
            font_size: "20dp"
            height: "50dp"
            size_hint_y: None